# ===============================================================
# FICHIER DE PRODUCTION
# Utiliser ce fichier pour le déploiement.
# Commande: docker-compose -f docker-compose.prod.yml up --build
# ===============================================================
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3001:3001"
    # La politique de redémarrage assure que le service se relance
    # en cas de crash ou au redémarrage du serveur.
    restart: unless-stopped
