CREATE TABLE `absence_forecasts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`establishment_id` integer NOT NULL,
	`forecast_date` integer NOT NULL,
	`expected_absences` integer NOT NULL,
	`confidence` real NOT NULL,
	`specialization` text,
	`shift` text,
	`factors` text DEFAULT '{}',
	`is_active` integer DEFAULT true,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`establishment_id`) REFERENCES `establishment_profiles`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `contract_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`establishment_id` text,
	`name` text(100) NOT NULL,
	`description` text,
	`is_default` integer DEFAULT false,
	`is_active` integer DEFAULT true,
	`template_html` text NOT NULL,
	`header_content` text,
	`footer_content` text,
	`available_variables` text,
	`signature_required` integer DEFAULT true,
	`auto_send` integer DEFAULT true,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`establishment_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `contracts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`mission_id` integer NOT NULL,
	`nurse_id` text NOT NULL,
	`establishment_id` text NOT NULL,
	`contract_number` text(50) NOT NULL,
	`title` text(200) NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer NOT NULL,
	`hourly_rate` real NOT NULL,
	`total_hours` real NOT NULL,
	`total_amount` real NOT NULL,
	`contract_content` text NOT NULL,
	`contract_pdf` text,
	`status` text DEFAULT 'generated' NOT NULL,
	`nurse_signature` text,
	`establishment_signature` text,
	`legal_terms` text,
	`governing_law` text(100) DEFAULT 'Droit français',
	`sent_to_nurse_at` integer,
	`sent_to_establishment_at` integer,
	`reminders_sent` integer DEFAULT 0,
	`generated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`mission_id`) REFERENCES `missions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`nurse_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`establishment_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `contracts_contract_number_unique` ON `contracts` (`contract_number`);--> statement-breakpoint
CREATE TABLE `documents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`filename` text NOT NULL,
	`original_name` text NOT NULL,
	`mime_type` text NOT NULL,
	`size` integer NOT NULL,
	`type` text NOT NULL,
	`is_verified` integer DEFAULT false,
	`url` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `establishment_profiles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`siret` text,
	`type` text NOT NULL,
	`address` text NOT NULL,
	`city` text NOT NULL,
	`postal_code` text NOT NULL,
	`phone` text,
	`website` text,
	`contact_person_name` text,
	`contact_person_email` text,
	`contact_person_phone` text,
	`capacity` integer,
	`bed_count` integer,
	`specialties` text DEFAULT '[]',
	`specializations` text DEFAULT '[]',
	`services` text DEFAULT '[]',
	`description` text,
	`rating` real DEFAULT 0,
	`total_missions` integer DEFAULT 0,
	`latitude` real,
	`longitude` real,
	`custom_scoring_enabled` integer DEFAULT false,
	`selected_criteria` text DEFAULT '[]',
	`custom_weights` text DEFAULT '{}',
	`specific_criterion` text,
	`specific_criterion_weight` integer DEFAULT 10,
	`is_active` integer DEFAULT true,
	`is_verified` integer DEFAULT false,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `establishment_profiles_siret_unique` ON `establishment_profiles` (`siret`);--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`mission_id` integer NOT NULL,
	`nurse_id` integer NOT NULL,
	`establishment_id` integer NOT NULL,
	`amount` real NOT NULL,
	`currency` text DEFAULT 'EUR',
	`tax_rate` real DEFAULT 0.2,
	`tax_amount` real NOT NULL,
	`total_amount` real NOT NULL,
	`status` text DEFAULT 'draft',
	`issued_at` integer,
	`due_at` integer,
	`paid_at` integer,
	`invoice_number` text,
	`payment_reference` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`mission_id`) REFERENCES `missions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`nurse_id`) REFERENCES `nurse_profiles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`establishment_id`) REFERENCES `establishment_profiles`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `invoices_invoice_number_unique` ON `invoices` (`invoice_number`);--> statement-breakpoint
CREATE TABLE `mission_applications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`mission_id` integer NOT NULL,
	`nurse_id` integer NOT NULL,
	`status` text DEFAULT 'pending',
	`cover_letter` text,
	`establishment_feedback` text,
	`ai_score` real,
	`ai_reasons` text DEFAULT '[]',
	`applied_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`responded_at` integer,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`mission_id`) REFERENCES `missions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`nurse_id`) REFERENCES `nurse_profiles`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `mission_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`establishment_id` text NOT NULL,
	`name` text(100) NOT NULL,
	`description` text,
	`category` text(50),
	`is_default` integer DEFAULT false,
	`is_active` integer DEFAULT true,
	`title` text(200) NOT NULL,
	`specialization` text(100) NOT NULL,
	`requirements` text,
	`responsibilities` text,
	`hourly_rate` real,
	`shift_duration` integer DEFAULT 8,
	`preferred_shifts` text DEFAULT '[]',
	`urgency_level` text DEFAULT 'medium',
	`min_experience` integer DEFAULT 0,
	`required_certifications` text DEFAULT '[]',
	`preferred_specializations` text DEFAULT '[]',
	`tags` text DEFAULT '[]',
	`estimated_duration` integer,
	`max_distance` integer DEFAULT 50,
	`usage_count` integer DEFAULT 0,
	`last_used_at` integer,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`establishment_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `missions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`establishment_id` integer NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`specialization` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer NOT NULL,
	`start_time` text,
	`end_time` text,
	`shift` text,
	`hours_per_day` real DEFAULT 8,
	`duration_days` integer DEFAULT 1,
	`hourly_rate` real NOT NULL,
	`total_hours` real,
	`required_experience` integer DEFAULT 0,
	`required_certifications` text DEFAULT '[]',
	`urgency_level` text DEFAULT 'medium',
	`status` text DEFAULT 'draft',
	`selected_nurse_id` integer,
	`ai_matching_score` real,
	`application_count` integer DEFAULT 0,
	`address` text,
	`city` text,
	`postal_code` text,
	`latitude` real,
	`longitude` real,
	`contract_type` text DEFAULT 'cdd',
	`is_template` integer DEFAULT false,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`establishment_id`) REFERENCES `establishment_profiles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`selected_nurse_id`) REFERENCES `nurse_profiles`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `nurse_profiles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`first_name` text,
	`last_name` text,
	`phone` text,
	`date_of_birth` text,
	`address` text,
	`city` text,
	`postal_code` text,
	`license_number` text,
	`experience` integer DEFAULT 0,
	`specializations` text DEFAULT '[]',
	`certifications` text DEFAULT '[]',
	`rating` real DEFAULT 0,
	`completed_missions` integer DEFAULT 0,
	`total_earnings` real DEFAULT 0,
	`availability` text DEFAULT '{}',
	`max_distance` integer DEFAULT 50,
	`hourly_rate_min` real,
	`hourly_rate_max` real,
	`preferred_shifts` text DEFAULT '[]',
	`preferred_specializations` text DEFAULT '[]',
	`is_active` integer DEFAULT true,
	`is_verified` integer DEFAULT false,
	`latitude` real,
	`longitude` real,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `nurse_profiles_license_number_unique` ON `nurse_profiles` (`license_number`);--> statement-breakpoint
CREATE TABLE `sessions` (
	`sid` text PRIMARY KEY NOT NULL,
	`sess` blob NOT NULL,
	`expire` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text,
	`first_name` text,
	`last_name` text,
	`profile_image_url` text,
	`password_hash` text,
	`role` text DEFAULT 'nurse' NOT NULL,
	`language` text DEFAULT 'fr',
	`cgu_accepted` integer DEFAULT false,
	`cgu_accepted_at` integer,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)),
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);